development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:9493c0743b02e338da81ebc6d9e700ff@spinyfin.redistogo.com:11310/
  channel_prefix: XChange_production
